name: Backend tests and JaCoCo report # Nom du Workflow affiché dans l'interface Github Actions
run-name: ${{ github.actor }} is running backend tests and generating JaCoCo coverage reports 🚀

# Déclanche le workflow à chaque push ou pull request sur les branches main, develop etc...
on:
  push:
    branches: [main, develop, feat/*, fix/*]
  pull_request:
    branches: [main, develop, feat/*, fix/*]
    types: [opened, synchronize, reopened]

# Définit un job nommé Backend-test qui s'execute sur une machine Virtuelle Unbuntu (Version la plus récente)
jobs:
  Backend-test:
    runs-on: ubuntu-latest

    # Définit `back` comme répertoire de travail par défaut pour toutes les étapes du job.
    defaults:
      run:
        working-directory: back

    # Utilise l'action checkout pour récupérer le code source du dépôt. 
    # actions/checkout@v4 est une version spécifique de cette action.
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # Utilise l'action setup-java pour configurer l'environnement Java.
      # Cela installe JDK 11 de la distribution temurin avec l'architecture x64
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with: 
          java-version: '11'
          distribution: 'temurin' # Options: 'temurin', 'zulu', 'adopt', 'oracle', 'microsoft', 'openjdk', 'amazon'
          architecture: x64       # Options: 'x64', 'x86', 'aarch64', 'armv7'
          cache: "maven"

      # Exécute la commande Maven mvn -B package pour compiler le projet et créer le package (jar/war). 
      # L'option -B (batch mode) supprime les invites interactives. 
      # La commande s'exécute sur le fichier pom.xml dans le répertoire de travail par défaut
      - name: Compile with Maven
        run: mvn -B compile --file pom.xml
        
      # Exécute la commande Maven mvn -B clean test pour nettoyer le répertoire de build précédent et exécuter les tests. 
      # Cela génère également un rapport de couverture Jacoco.  
      - name: Test with Maven
        run: mvn -B clean test

      - name: Package with Maven
        run: mvn -B package --file pom.xml -Dmaven.test.skip=true

      # Utilise l'action upload-artifact pour télécharger les fichiers de rapport de couverture générés par Jacoco. 
      # Ces fichiers sont stockés sous le nom jacoco-report et se trouvent dans le répertoire back/target/site/jacoco.
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: jacoco-report
          path: back/target/site/jacoco
