 # Nom du workflow et description de l'exécution
name: Build and push images to Docker Hub
run-name: ${{ github.actor }} is building and pushing front and back on docker-hub 🚀

# Déclenche le workflow sur les événements push et pull request sur les branches spécifiées
on:
  push:
    branches: [main, develop, feat/*, fix/*]
  pull_request:
    branches: [main, develop, feat/*, fix/*]
    types: [opened, synchronize, reopened]

# Définition des jobs
jobs:
  build:
    # Utilise la dernière version d'Ubuntu comme environnement d'exécution
    runs-on: ubuntu-latest

    # Liste des étapes du job
    steps:
      # Étape de checkout du code source
      - name: Checkout
        uses: actions/checkout@v4

      # Étape de connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Étape pour changer de répertoire vers le projet backend
      - name: Change directory to backend project root
        run: cd back

      # Configuration de Docker Buildx (outil pour la construction avancée d'images Docker)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Construction et push de l'image Docker pour le backend
      - name: Build and push backend Dockerfile
        uses: docker/build-push-action@v6
        with:
          context: ./back
          file: ./back/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-backend:latest

      # Étape pour changer de répertoire vers le projet frontend
      - name: Change directory to frontend project root
        run: cd front

      # Configuration de Docker Buildx pour le frontend
      - name: Set up Docker Buildx for frontend
        uses: docker/setup-buildx-action@v3

      # Construction et push de l'image Docker pour le frontend
      - name: Build and push frontend Dockerfile
        uses: docker/build-push-action@v6
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-frontend:latest