name: Frontend Workflow # Nom du Workflow affiché dans l'interface Github Actions
run-name: ${{ github.actor }} is running frontend workflows (Tests, Coverage, Docker, SonarCloud) 🚀

# Déclanche le workflow à chaque push ou pull request sur les branches main, develop etc...
on:
  push:
      branches: [main, develop, feat/*, fix/*]
  pull_request:
      branches: [main, develop, feat/*, fix/*]
      types: [opened, synchronize, reopened]
  
# Définit un job nommé Frontend-test qui s'exécute sur une machine Virtuelle Ubuntu (Version la plus récente)  
jobs:
  Frontend-test:
    runs-on: ubuntu-latest

    # Définit `front` comme répertoire de travail par défaut pour toutes les étapes du job.
    defaults:
      run:
        working-directory: front

    # Utilise une stratégie de matrice pour tester sur différentes versions de Node.js.
    strategy:
      matrix:
        node-version: [20.x] # Versions de Node.js à tester

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Utilise l'action checkout pour récupérer le code source du dépôt.
        with:
          fetch-depth: 0 # Les clones sont désactivés pour une meilleure pertinence de l'analyse.

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v4 # Utilise l'action setup-node pour configurer Node.js
        with:
          node-version: ${{matrix.node-version}} # Utilise la version de Node.js définie dans la matrice

      - name: Install dependencies
        run: npm ci # Installe les dépendances npm (npm install marche aussi)

      - name: Run npm test
        run: npm run test:prod # Exécute les tests sans watcher et en calculant la couverture

      - name: Build application
        run: npm run build # On vérifie que le projet se build correctement (compilation)
      
      - name: Upload coverage report
        uses: actions/upload-artifact@v4 # Utilise l'action upload-artifact pour télécharger les fichiers de rapport de couverture générés par Karma.
        if: success() || failure()
        with:
          name: karma-report
          path: front/coverage # Chemin vers les fichiers de rapport de couverture

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Étape de connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      # Étape pour changer de répertoire vers le projet backend
      - name: Change directory to backend project root
        run: cd back
  
      # Configuration de Docker Buildx (outil pour la construction avancée d'images Docker)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      # Configuration de Docker Buildx pour le frontend
      - name: Set up Docker Buildx for frontend
        uses: docker/setup-buildx-action@v3
  
      # Construction et push de l'image Docker pour le frontend
      - name: Build and push frontend Dockerfile
        uses: docker/build-push-action@v6
        with:
            context: ./front
            file: ./front/Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-frontend:latest