name: 'Test Report'
on:
  workflow_run:
    workflows: ['Backend tests and JaCoCo report']                     # runs after CI workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: phoenix-actions/test-reporting@v15
      id: test-report                     # Set ID reference for step
      with:
        artifact: jacoco-report           # artifact name
        name: Jacoco Tests                # Name of the check run which will be created
        path: '*.xml'                     # Path to test results (inside artifact .zip)
        reporter: java-junit              # Format of test results