name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'  # Vous pouvez également utiliser 'zulu' ou 'temurin'
        java-version: 11

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn -B clean install

    - name: Run tests with Maven
      run: mvn test

    - name: Build Docker image
      run: docker build -t bobapp:latest .

    - name: Run Docker container
      run: docker run -d -p 8080:8080 bobapp:latest

    - name: Wait for the server to be ready
      run: |
        retries=10
        while [ $retries -gt 0 ]; do
          response=$(curl --write-out "%{http_code}" --silent --output /dev/null http://localhost:8080/actuator/health)
          if [ $response -eq 200 ]; then
            echo "Server is up!"
            break
          fi
          echo "Waiting for the server..."
          sleep 10
          retries=$((retries - 1))
        done

    - name: Run integration tests
      run: |
        echo "Running integration tests..."
        # Exécutez vos tests d'intégration ici

